spring.application.name=kotlin-spring-mongo-crud


spring.mongodb.uri=mongodb://localhost:27017/userdb

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG


#spring.data.redis.host=localhost
#spring.data.redis.port=63798




